### PR TITLE
[10.0] purchase_request_operating_unit

### PR DESCRIPTION
**Pull request by AaronHForgeFlow**
Supersedes #80 

It also adds the following features:

- passes the OU from the purchase request to the RFQ
- passes the OU from the purchase request to the Requisition
- passes the OU from a procurement to the Purchase Request

### CODE REVIEW

**Comment by JordiBForgeFlow** [comment]
@aheficent Please split into the separate modules.

**Comment by MiquelRForgeFlow** [comment]
Moved the `purchase_request_to_requisition_operating_unit` module to https://github.com/OCA/operating-unit/pull/135.

**Review by MiquelRForgeFlow — APPROVED** [review]
LGTM

**Review by JordiBForgeFlow — APPROVED** [review]
Tested functionally

**Pull request merged**
