### PR TITLE
[ADD][10.0]account_invoice_qweb_operating_unit

### PR DESCRIPTION
**Pull request by AaronHForgeFlow**
Adds the Operating unit information to the invoice printout.

Depends on:
- [x] https://github.com/OCA/operating-unit/pull/95

### CODE REVIEW

**Comment by pankk** [comment]
Failing because this depends on report_qweb_operating_unit. That is available here: https://github.com/OCA/operating-unit/pull/68
That depends on https://github.com/OCA/operating-unit/pull/80 which is pending to be rebased by @darshan-serpent 

Installed and printed the report after manually adding the dependencies. Prints as expected.
👍

**Comment by serpentcs-dev1** [comment]
@pankk The branch you mentioned is already rebased, which is also waiting for another [dependent PR](https://github.com/OCA/purchase-workflow/pull/368) :hourglass:

**Comment by AaronHForgeFlow** [comment]
@pankk  thanks a lot for your review. Would you please use the git approval method so we can make it count?

image

Thanks! :smiley:

**Review by MiquelRForgeFlow — APPROVED** [review]
LGTM

**Review by pankk — APPROVED** [review]

**Pull request merged**
