### PR TITLE
[13.0][MIG] mrp_operating_unit

### PR DESCRIPTION
**Pull request by BT-nstuder**
## Proposed changes

I've migrated the module `mrp_operating_unit` and it's functionalities from Odoo `12.0` to `13.0`. I've checked if the all unit tests are still running.

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [X] Migration Update

## Checklist

- [x] I have read the [CONTRIBUTING](https://github.com/OCA/odoo-community.org/blob/master/website/Contribution/CONTRIBUTING.rst) doc
- [x] I have signed the [CLA](https://odoo-community.org/page/cla)
- [x] Lint and unit tests pass locally with my changes
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have updated necessary documentation

## Further comments

I didn't change any logic of the module, but I refactored the method `_check_location_operating_unit` in `mrp.py` and removed some redundancy in it.

This module depends on the `stock_operating_unit` module. That means that there should be a migration of it to `13.0`. Because there is already a PR for a migration I've added the changes of the PR to my local environment to test my migration.

This PR depends on the current migration PR #231.

### CODE REVIEW

**Comment by AaronHForgeFlow** [comment]
Hi @BT-nstuder, could you rebase your branch? stock_operating_unit is merged so this should be ready to review.

**Comment by BT-nstuder** [comment]
Hello @AaronHForgeFlow, branch is rebased with newest `13.0` and xml files are reformatted with prettier as well.

**Comment by AaronHForgeFlow** [comment]
When creating MO from scratch, users should be able to change the operating unit in the manufacturing order (among the operating units they are assigned to ). Currently, that field is not editable in the manufacturing order view:

image

**Comment by AaronHForgeFlow** [comment]
Apart of that, t would be great having an onchange in the manufacturing locations based on the warehouse of the operating unit. Now, if I change the operating unit of a manufacturing order to B2C the locations in the manufacturing order remains as "WH/Stock".

Apart of that I think this PR works correctly.

Thanks.

**Comment by BT-nstuder** [comment]
Hi @AaronHForgeFlow, thanks for the review. I've implemented your suggestions. I've committed the changes with a new commit (d0c6138) because they are independent from the migration itself.

As you can see by changing the `operating_unit_id` it tries to find the first valid picking type for the new operating unit. I hope this is what you meant.

**Review by AaronHForgeFlow — APPROVED** [review]
Thank you @BT-nstuder. I tested and this works well.

**Review by alan196 — APPROVED** [review]
👍 Functional & Technical Review

**Pull request merged**
