### PR TITLE
[10.0] [ADD] sale_order_qweb_operating_unit

### PR DESCRIPTION
**Pull request by nikul-serpentcs**
Sale Order Qweb Report With Operating Unit
==========================================

* This module sale report by a Qweb report and also adds the Operating Unit information to it.

### CODE REVIEW

**Comment by nikul-serpentcs** [comment]
@aheficent Could you please review.

**Review by AaronHForgeFlow — COMMENTED** [review]
Hi @nikul-serpentcs Please only keep the headers and the div with operating unit name. The other part is a customization and has to be put in another module

**Comment by AaronHForgeFlow** [comment]
Depends on https://github.com/OCA/operating-unit/pull/95

**Review by AaronHForgeFlow — APPROVED** [review]
:+1: Testing in local with https://github.com/OCA/operating-unit/pull/95. Working fine.

**Comment by AaronHForgeFlow** [comment]
Maybe it's a good idea to add the dependency to https://github.com/OCA/operating-unit/pull/95 in oca_dependencies.txt file so others can test on runbot

**Comment by nikul-serpentcs** [comment]
@aheficent Added dependency in oca_dependencies.txt file Could you please review.

**Comment by AaronHForgeFlow** [comment]
@nikul-serpentcs Something went wrong with the dependencies :face_with_head_bandage:

**Comment by nikul-serpentcs** [comment]
@aheficent Added dependency, Could you please review.

**Review by AaronHForgeFlow — APPROVED** [review]
:+1: It's fine now

**Comment by AaronHForgeFlow** [comment]
Agreed with the author to take over this PR #123

**Pull request closed without merging**
