### PR TITLE
[15.0][MIG] hr_expense_operating_unit

### PR DESCRIPTION
**Pull request by Saran440**
This PR continue from https://github.com/OCA/operating-unit/pull/449

- Edit commit to original
- Delete import test in init file

### CODE REVIEW

**Comment by JuanyDForgeflow** [comment]
@Saran440 I was testing with admin user who has access to all operating units

image
image

But in only allows me to select the main one

image

If I change the default to another ou (Ex: B2C) it's selected on creation but the domain only shows the main ou on the selection.

image

**Comment by Saran440** [comment]
@JuanyDForgeflow Thank you for your review. I fixed it.
- Delete domain users
- Add group by operating unit in expense and expense sheet
Selection_017

**Review by JuanyDForgeflow — APPROVED** [review]
It's working fine now, thanks for the fix!

**Comment by Saran440** [comment]
Last commit fix bug can't register payment with config self-balance
and this PR will depend on https://github.com/OCA/operating-unit/pull/581

**Review by ps-tubtim — APPROVED** [review]
Functional Test: OK

**Review by AaronHForgeFlow — APPROVED** [review]
code review

**Pull request merged**
