### PR TITLE
[FIX] This line leads the test to an error but the module is well installed 

### PR DESCRIPTION
**Pull request by nikul-serpentcs**
Issue: #291

### CODE REVIEW

**Review by JordiBForgeFlow — APPROVED** [review]

**Comment by JordiBForgeFlow** [comment]
@nikul-serpentcs please check travis

**Comment by nikul-serpentcs** [comment]
@JordiBForgeFlow Sure

**Comment by nikul-serpentcs** [comment]
@JordiBForgeFlow  Mr.Travis is :green_apple:  
Ready to merge

**Comment by JordiBForgeFlow** [comment]
Thank you!!

**Pull request merged**
