### PR TITLE
Fix constraint on warehouses

### PR DESCRIPTION
**Pull request by guewen**

### CODE REVIEW

**Review by elicoidal — APPROVED** [review]
:+1:

**Review by JordiBForgeFlow — APPROVED** [review]
:+1: Thanks!

**Comment by JordiBForgeFlow** [comment]
cc @mreficent

**Review by AaronHForgeFlow — APPROVED** [review]
:+1: Thanks

**Review by MiquelRForgeFlow — APPROVED** [review]
:+1:

**Pull request merged**
