### PR TITLE
[FIX] res_partner_operating_unit: Perf issue (#258)

### PR DESCRIPTION
**Pull request by max3903**
#258

### CODE REVIEW

**Review by patrickrwilson — APPROVED** [review]
LGTM

**Review by AaronHForgeFlow — APPROVED** [review]
:+1:  LGTM

**Comment by max3903** [comment]
TODO: Extend the `search()` method to add the OU arguments.

**Review by andreampiovesana — COMMENTED** [review]
i added name search https://github.com/max3903
https://github.com/OCA/operating-unit/pull/305
can you review?

**Pull request merged**
