### PR TITLE
[14.0][ADD] purchase_request_operating_unit_access_all

### PR DESCRIPTION
**Pull request by kittiu**
New group to access all OU's purchase requests

### CODE REVIEW

**Review by JordiBForgeFlow — APPROVED** [review]

**Comment by AaronHForgeFlow** [comment]
can you check travis?

**Comment by kittiu** [comment]
> can you check travis?

OK now.

**Comment by AaronHForgeFlow** [comment]
Good, thanks, can you squash your commits? the bot is not able to do so

**Review by newtratip — APPROVED** [review]
LGTM :+1:

**Review by AaronHForgeFlow — APPROVED** [review]

**Pull request merged**
