### PR TITLE
[15.0] [MIG] hr_expense_operating_unit

### PR DESCRIPTION
**Pull request by Rajan-SCS**

### CODE REVIEW

**Comment by JuanyDForgeflow** [comment]
@Rajan-SCS Do you plan to continue this migration?

**Comment by AaronHForgeFlow** [comment]
Sorry @Rajan-SCS , but you have to create a new PR because it is not technically possible to reopen this

**Comment by BT-dherreros** [comment]
@Rajan-SCS LGTM. But you should open a new PR as @AaronHForgeFlow commented before me.

**Comment by AaronHForgeFlow** [comment]
It seems this is open again :)

**Comment by Saran440** [comment]
@Rajan-SCS Hello,

I open new PR for continue migration is here https://github.com/OCA/operating-unit/pull/574
Can you close this PR and help review, please?

**Pull request closed without merging**
