### PR TITLE
[IMP] Default Operating Unit Company Dependant

### PR DESCRIPTION
**Pull request by osi-scampbell**
This PR makes Default Operating Unit on a Res User company dependant

### CODE REVIEW

**Review by alan196 — APPROVED** [review]
👍 Good addition

**Review by AaronHForgeFlow — APPROVED** [review]
:+1: Good!

**Comment by Espzai** [comment]
Hi @osi-scampbell ,
There is a spell mistake in depend**_a_**nt.
It should be 

> company_dependent=True
Regards.

**Comment by AaronHForgeFlow** [comment]
@Espzai @osi-scampbell My fault. I will fix it here: #247

**Pull request merged**
