### PR TITLE
[14.0][MIG] hr_expense_operating_unit

### PR DESCRIPTION
**Pull request by kittiu**
Standard migration
Depends,
- [x] account_operating_unit https://github.com/OCA/operating-unit/pull/332

### CODE REVIEW

**Comment by Saran440** [comment]
@kittiu please, update travis and cherry-pick https://github.com/OCA/operating-unit/pull/360

**Comment by kittiu** [comment]
> @kittiu please, update travis and cherry-pick #360

Done

**Review by Saran440 — APPROVED** [review]
Functional Test :+1:

**Comment by Saran440** [comment]
cherry-pick #368

**Comment by AaronHForgeFlow** [comment]
It seems there is a bug in the account_operating_unit module, probably because of a change in Odoo standard (a new constraint?). The last commit in 14.0 branch is from January so it is quite old. If nobody proposes a fix I will try to do that soon.

**Comment by kittiu** [comment]
I will propose the fix now.

**Comment by kittiu** [comment]
> It seems there is a bug in the account_operating_unit module, probably because of a change in Odoo standard (a new constraint?). The last commit in 14.0 branch is from January so it is quite old. If nobody proposes a fix I will try to do that soon.

Done here, https://github.com/OCA/operating-unit/pull/370

**Review by AaronHForgeFlow — COMMENTED** [review]
Functional test on runbot:
User admin is assigned to all OUs:
image

However it cannot select other but the default OU in hr expense report and expense:
image

I understand I should be able to select any of the OUs I am assign to.

**Comment by kittiu** [comment]
If you type it in, it will be found. We also face this, but not the problem of this module may be from base operating_unit itself.

I will check that too.

**Comment by AaronHForgeFlow** [comment]
Thank you for the update, yes, it not really an issue because you can type and select a different one. And it does not seem an issue in this module.

**Review by AaronHForgeFlow — APPROVED** [review]

**Pull request merged**
