### PR TITLE
[15.0] [MIG] hr_payroll_account_operating_unit

### PR DESCRIPTION
**Pull request by olveracuenca**

### CODE REVIEW

**Comment by AaronHForgeFlow** [comment]
Depends on https://github.com/OCA/payroll/tree/15.0/payroll_account

**Comment by olveracuenca** [comment]
@AaronHForgeFlow thank you

**Review by AaronHForgeFlow — COMMENTED** [review]
Functional LG. just one, thing, if in the salary rule I don't select taxes I get an error when confirming the payslip:



`Traceback (most recent call last):
  File "/opt/odoo/odoo/addons/base/models/ir_http.py", line 237, in _dispatch
    result = request.dispatch()
  File "/opt/odoo/odoo/http.py", line 687, in dispatch
    result = self._call_function(**self.params)
  File "/opt/odoo/odoo/http.py", line 359, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/odoo/odoo/service/model.py", line 94, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/odoo/odoo/http.py", line 348, in checked_call
    result = self.endpoint(*a, **kw)
  File "/opt/odoo/odoo/http.py", line 916, in __call__
    return self.method(*args, **kw)
  File "/opt/odoo/odoo/http.py", line 535, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo/addons/web/controllers/main.py", line 1346, in call_button
    action = self._call_kw(model, method, args, kwargs)
  File "/opt/odoo/addons/web/controllers/main.py", line 1334, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/opt/odoo/odoo/api.py", line 464, in call_kw
    result = _call_kw_multi(method, model, args, kwargs)
  File "/opt/odoo/odoo/api.py", line 451, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/opt/odoo-venv/lib/python3.8/site-packages/odoo/addons/payroll_account/models/hr_payroll_account.py", line 269, in action_payslip_done
    move = self.env["account.move"].create(move_dict)
  File "<decorator-gen-197>", line 2, in create
  File "/opt/odoo/odoo/api.py", line 412, in _model_create_multi
    return create(self, [arg])
  File "/opt/odoo/addons/account/models/account_move.py", line 2337, in create
    return super(AccountMove, self).create(vals_list)
  File "<decorator-gen-132>", line 2, in create
  File "/opt/odoo/odoo/api.py", line 413, in _model_create_multi
    return create(self, arg)
  File "/opt/odoo/addons/mail/models/mail_thread.py", line 265, in create
    threads = super(MailThread, self).create(vals_list)
  File "<decorator-gen-67>", line 2, in create
  File "/opt/odoo/odoo/api.py", line 413, in _model_create_multi
    return create(self, arg)
  File "/opt/odoo/odoo/addons/base/models/ir_fields.py", line 613, in create
    recs = super().create(vals_list)
  File "<decorator-gen-13>", line 2, in create
  File "/opt/odoo/odoo/api.py", line 413, in _model_create_multi
    return create(self, arg)
  File "/opt/odoo/odoo/models.py", line 4079, in create
    records = self._create(data_list)
  File "/opt/odoo/odoo/models.py", line 4229, in _create
    field.create([
  File "/opt/odoo/odoo/fields.py", line 3291, in create
    self.write_batch(record_values, True)
  File "/opt/odoo/odoo/fields.py", line 3317, in write_batch
    return self.write_real(records_commands_list, create)
  File "/opt/odoo/odoo/fields.py", line 3493, in write_real
    flush()
  File "/opt/odoo/odoo/fields.py", line 3455, in flush
    comodel.create(to_create)
  File "<decorator-gen-209>", line 2, in create
  File "/opt/odoo/odoo/api.py", line 413, in _model_create_multi
    return create(self, arg)
  File "/mnt/data/odoo-addons-dir/account_operating_unit/models/account_move.py", line 23, in create
    return super().create(vals_list)
  File "<decorator-gen-198>", line 2, in create
  File "/opt/odoo/odoo/api.py", line 413, in _model_create_multi
    return create(self, arg)
  File "/opt/odoo/addons/account/models/account_move.py", line 4701, in create
    lines = super(AccountMoveLine, self).create(vals_list)
  File "<decorator-gen-67>", line 2, in create
  File "/opt/odoo/odoo/api.py", line 413, in _model_create_multi
    return create(self, arg)
  File "/opt/odoo/odoo/addons/base/models/ir_fields.py", line 613, in create
    recs = super().create(vals_list)
  File "<decorator-gen-13>", line 2, in create
  File "/opt/odoo/odoo/api.py", line 413, in _model_create_multi
    return create(self, arg)
  File "/opt/odoo/odoo/models.py", line 4079, in create
    records = self._create(data_list)
  File "/opt/odoo/odoo/models.py", line 4229, in _create
    field.create([
  File "/opt/odoo/odoo/fields.py", line 3291, in create
    self.write_batch(record_values, True)
  File "/opt/odoo/odoo/fields.py", line 3317, in write_batch
    return self.write_real(records_commands_list, create)
  File "/opt/odoo/odoo/fields.py", line 3889, in write_real
    cr.execute(query, pairs)
  File "<decorator-gen-3>", line 2, in execute
  File "/opt/odoo/odoo/sql_db.py", line 90, in check
    return f(self, *args, **kwargs)
  File "/opt/odoo/odoo/sql_db.py", line 313, in execute
    res = self._obj.execute(query, params)
Exception

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/odoo/odoo/http.py", line 643, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo/odoo/http.py", line 301, in _handle_exception
    raise exception.with_traceback(None) from new_cause
psycopg2.errors.DatatypeMismatch: column "account_tax_id" is of type integer but expression is of type boolean
LINE 1: ...account_move_line_id, account_tax_id) VALUES (38, false), (3...
                                                             ^
HINT:  You will need to rewrite or cast the expression.`

**Comment by AaronHForgeFlow** [comment]
Hi @olveracuenca , I did another test and the error is gone, I think it was fixed in the account_operating_unit module. I did a rebase and created another PR here: https://github.com/OCA/operating-unit/pull/604 The rebase was needed because of another fix in the hr_contract_operating_unit module. If you don't mind we will continue in the other PR, otherwise please let me know.

**Comment by AaronHForgeFlow** [comment]
Superseded and merged. Closing.

**Pull request closed without merging**
