### PR TITLE
[13.0][MIG] migration of module stock_account_operating_unit

### PR DESCRIPTION
**Pull request by alan196**
### Proposed changes

I've migrated the module stock_account_operating_unit and it's functionalities from Odoo 12.0 to 13.0. I've checked if the all unit tests are still running.

### Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Migration Update

### Checklist

- [x] I have read the CONTRIBUTING doc
- [x] I have signed the CLA
- [x] Lint and unit tests pass locally with my changes
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have updated necessary documentation

### Further comments

This module depends on the account_operating_unit  and stock_operating_unit module. That means that there should be a migration of it to 13.0. Because there is already a PR for migration I've added the changes of the PR to my local environment to test my migration.

This PR depends on the current migration PR:

https://github.com/OCA/operating-unit/pull/229
https://github.com/OCA/operating-unit/pull/231

### CODE REVIEW

**Review by robyf70 — APPROVED** [review]
LGTM

**Comment by luistriana28** [comment]
👍

**Comment by mmena9** [comment]
(Y)

**Comment by mmena9** [comment]
👍

**Review by mmena9 — APPROVED** [review]

**Review by newtratip — APPROVED** [review]
LGTM :+1:

**Review by AaronHForgeFlow — APPROVED** [review]
Code review :+1:

**Review by AaronHForgeFlow — APPROVED** [review]
Functional tests too

**Pull request merged**
