### PR TITLE
[14.0][FIX]purchase_operating_unit: Operating Unit Issue when creating RFQ in Purchase App

### PR DESCRIPTION
**Pull request by Vimal-OSI**
If you have a default OU set on your user get the following error when creating a RFQ "No Warehouse found with the Operating Unit indicated in the Purchase Order"

### CODE REVIEW

**Comment by kittiu** [comment]
@Vimal-OSI just curious. What is the benefit of this fix, except you are using onchange instead of UserError?

Just curious, I might not technically enough to understand :)

**Comment by Vimal-OSI** [comment]
> @Vimal-OSI just curious. What is the benefit of this fix, except you are using onchange instead of UserError?
> 
> Just curious, I might not technically enough to understand :)

Well!, If we have used "raise UserError" on On change method then It's blocks process if condition is satisfied. (I believe, It's not good practice to raise warning on on-change method).
instead of it, we can use return warning, then won't be block process but raised alert to user too.

**Comment by AaronHForgeFlow** [comment]
If the user tries to confirm the PO and he gets an error then this is fine to me. And that is what it is happening I believe

**Comment by AaronHForgeFlow** [comment]
Hi @Vimal-OSI, can you please explain the exact steps to reproduce the issue? I tried the following: assign myself the operating unit B2B as default. Then create an RFQ and the default picking type for B2B receipts was selected, then I tried to modify the picking type field but I got no errors no warning messages.

**Review by max3903 — APPROVED** [review]

**Pull request closed without merging**
