### PR TITLE
[14.0][MIG] project_operating_unit

### PR DESCRIPTION
**Pull request by Murtaza-OSI**

### CODE REVIEW

**Review by patrickrwilson — APPROVED** [review]
Tested and works, code looks good. LGTM

**Comment by max3903** [comment]
@Urvisha-OSI Can you fix that PR please?

**Comment by Urvisha-OSI** [comment]
> @Urvisha-OSI Can you fix that PR please?



> @Urvisha-OSI Can you fix that PR please?

@max3903 the pre-commit fails reason is black version is old in pre-commit.yml file need to merge first https://github.com/OCA/operating-unit/pull/516 this PR in 14.0 branch and then merge the current PR so pre-commit issue is solved

**Comment by Urvisha-OSI** [comment]
> @Urvisha-OSI Can you fix that PR please?

@max3903 as i check for this PR we have the old black version in our ursais branch and OCA have the new one the reason of this PR fails it this.
i made a new PR for ursais 14.0 branch https://github.com/ursais/operating-unit/pull/16
we need to merge it first in our ursais branch and then this error will solve automatically

**Review by max3903 — APPROVED** [review]

**Review by blitzkrieg-ar — APPROVED** [review]

**Pull request merged**
