### PR TITLE
[14.0][MIG] sale_crm_operating_unit

### PR DESCRIPTION
**Pull request by JuanyDForgeflow**
This module introduces the following features:

* Passes the Operating Unit (OU) from Opportunity to Quotation.

### CODE REVIEW

**Comment by JuanyDForgeflow** [comment]
This module is dependent on https://github.com/OCA/operating-unit/pull/487

**Comment by JuanyDForgeflow** [comment]
@AaronHForgeFlow I'm not sure why runbot isn't working

image

**Review by AaronHForgeFlow — APPROVED** [review]
Functional review LG!

**Review by JasminSForgeFlow — APPROVED** [review]
Functional review

**Pull request merged**
