### PR TITLE
[15.0][MIG] hr_contract_operating_unit

### PR DESCRIPTION
**Pull request by JuanyDForgeflow**
This module introduces the following features:

* Adds the Operating Unit (OU) to the Employee Contract.

* Security rules are defined to ensure that users can only see the Contracts of that Operating Units in which they are allowed access to.

### CODE REVIEW

**Review by BT-apadron — APPROVED** [review]
LGTM

**Comment by AaronHForgeFlow** [comment]
@JuanyDForgeflow  can you check pre-commit?

**Comment by JuanyDForgeflow** [comment]
@AaronHForgeFlow Done

**Review by AaronHForgeFlow — CHANGES_REQUESTED** [review]
Tested on runbot, When creating a new contract I cannot create a new contract in a different operating unit that main operating unit. If I put B2B as the default operating unit, The contract will have this operating unit, but if I try to select any other, then only Main OU is available again.

**Comment by JuanyDForgeflow** [comment]
@AaronHForgeFlow It's fixed now

**Review by AaronHForgeFlow — APPROVED** [review]
Functional tests

**Pull request merged**
