### PR TITLE
[12.0][FIX] hr_payroll_account_operating_unit

### PR DESCRIPTION
**Pull request by MiquelRForgeFlow**
Forward port of https://github.com/OCA/operating-unit/pull/352.

### CODE REVIEW

**Review by AaronHForgeFlow — APPROVED** [review]

**Comment by AaronHForgeFlow** [comment]
/ocabot merge nobump

Fasttracking as clear bug and forward port

**Comment by AaronHForgeFlow** [comment]
/ocabot merge patch

Fasttracking as clear bug and forward port

**Comment by MiquelRForgeFlow** [comment]
@sbidoul something is wrong here with ocabot.

**Comment by AaronHForgeFlow** [comment]
> @sbidoul something is wrong here with ocabot.

My bad. I invoked the ocabot twice by mistake, sorry.

**Pull request merged**
