### PR TITLE
[15.0][FIX] Fix operating unit payment tests

### PR DESCRIPTION
**Pull request by robyf70**
Fix the operating unit payment tests

### CODE REVIEW

**Comment by robyf70** [comment]
It seems there some issue with the **pre-commit run -a** because it's formatting automatically but it fails the checks

**Review by AaronHForgeFlow — APPROVED** [review]
Thanks

**Comment by AaronHForgeFlow** [comment]
> It seems there some issue with the **pre-commit run -a** because it's formatting automatically but it fails the checks

perhaps copier template needs an update. Will do on a separate PR.

**Review by MiquelRForgeFlow — APPROVED** [review]

**Comment by AaronHForgeFlow** [comment]
/ocabot merge nobump 

Thanks

**Pull request merged**
