### PR TITLE
[15.0] [MIG] sales_team_operating_unit

### PR DESCRIPTION
**Pull request by Rajan-SCS**

### CODE REVIEW

**Review by alan196 — APPROVED** [review]
LGTM

**Comment by alan196** [comment]
Just fix pre-commit

**Comment by Rajan-SCS** [comment]
@alan196  Fixed the pre-commit

**Comment by Rajan-SCS** [comment]
@AaronHForgeFlow @nikul-serpentcs can you please take a look?

**Review by AaronHForgeFlow — DISMISSED** [review]
Functional review

**Comment by AaronHForgeFlow** [comment]
What I dont understand is why the commit messages have been amended:
image

**Comment by Rajan-SCS** [comment]
@AaronHForgeFlow could you please check the PR

**Review by AaronHForgeFlow — APPROVED** [review]
Now it looks good :)

**Review by nikul-serpentcs — APPROVED** [review]
Code review LGTM :+1: 


@AaronHForgeFlow ready to merge

**Pull request merged**
