### PR TITLE
[14.0][IMP] travis to github-actions

### PR DESCRIPTION
**Pull request by AaronHForgeFlow**
@ForgeFlow

### CODE REVIEW

**Comment by AaronHForgeFlow** [comment]
@sbidoul @gurneyalex  sorry for ping you here. But I cannot make github actions to run tests on this repo. Do you know what I have to do? Thanks in advance.

**Comment by sbidoul** [comment]
@AaronHForgeFlow `.test copy.yml` does not look like the correct file name. Also 1.5.2 is not the latest version of the template.
Did you run `copier update` to update the config ?

**Comment by AaronHForgeFlow** [comment]
Thank you @sbidoul I was doing some tests, and I uploaded the wrong file. Also the copier update was failing before. Now it works. Thanks for the help :)

**Comment by AaronHForgeFlow** [comment]
@sbidoul @kittiu  FYI: I am fixing the license on the mis-builder modules on this repo, they should be AGPL.

@kittiu FYI I am adding a development status for account_asset_operating_unit_access_all. It is the same as its dependency

**Comment by AaronHForgeFlow** [comment]
fail

**Review by MiquelRForgeFlow — APPROVED** [review]

**Pull request merged**
