### PR TITLE
[15.0][FIX] stock_operating_unit_access_all: domain_force in stock move is not correct

### PR DESCRIPTION
**Pull request by Saran440**
Step to error
1. Add permission stock all OU with user OU1
2. Login user OU1 and edit document with OU2 (It should allow edit because add permission stock all OU)
3. It still error
Selection_002

This PR fix domain_force in stock all OU

### CODE REVIEW

**Review by AaronHForgeFlow — APPROVED** [review]
Fastracking when green

**Comment by Saran440** [comment]
@AaronHForgeFlow This PR update domain include https://github.com/OCA/operating-unit/pull/619

**Review by ps-tubtim — APPROVED** [review]
LGTM

**Pull request merged**
