### PR TITLE
[12.0] [FIX] hr_expense_operating_unit: Fixed singleton error.

### PR DESCRIPTION
**Pull request by Chandresh-SerpentCS**

### CODE REVIEW

**Comment by Chandresh-SerpentCS** [comment]
@max3903 @osi-scampbell @murtuzasaleh PR reference FYI

**Review by alan196 — APPROVED** [review]
LGTM 👍 
Technical Review

**Review by Saran440 — APPROVED** [review]
Code Reviewed :+1:

**Pull request merged**
