### PR TITLE
[14.0][ADD] account_financial_report_operating_unit

### PR DESCRIPTION
**Pull request by kittiu**
Adding OU filter for,
- [x] General Ledger
- [x] Journal Ledger
- [x] Trial Balance
- [x] Open Items
- [x] Aged Partner Balance
- [x] VAT Report

### CODE REVIEW

**Comment by kittiu** [comment]
cc @AaronHForgeFlow, should be ready.

**Review by MeetKD — APPROVED** [review]
Functional & Code Review 👍

**Review by AaronHForgeFlow — COMMENTED** [review]
Functional tests LGTM. Just a minor nitpicking. Can you add a label to the operating unit field in the general ledger wizard view?

image

**Comment by kittiu** [comment]
> Functional tests LGTM. Just a minor nitpicking. Can you add a label to the operating unit field in the general ledger wizard view?

Thank you @AaronHForgeFlow for the review. The reason I don't have label is because I want it to be inline with other tabs, which seem to have no labels.

image


WDYT? If you have reason to have it, please let me know again :).

**Comment by AaronHForgeFlow** [comment]
I see, yes, better to be "aligned" then

**Review by AaronHForgeFlow — APPROVED** [review]

**Pull request merged**
