### PR TITLE
[15.0][MIG] mrp_operating_unit

### PR DESCRIPTION
**Pull request by JuanyDForgeflow**
This module introduces the following features:

* Adds Operating Unit (OU) to the Manufacturing Order created from the procurement.

* This module implements global security rules on manufacturing orders so that a user can only read manufacturing orders where the location is linked to an
  operating unit that the user has access to.

### CODE REVIEW

**Comment by JuanyDForgeflow** [comment]
This module has dependencies with  stock_operating_unit.

stock_operating_unit -> https://github.com/OCA/operating-unit/pull/439

**Comment by BT-pcavero** [comment]
Greeting @JuanyDForgeflow!
What is the current condition of this migration?

**Review by BT-pcavero — APPROVED** [review]
Looks good to me!

**Review by BT-apadron — APPROVED** [review]
LGTM

**Review by AaronHForgeFlow — APPROVED** [review]
LGTM

**Comment by JuanyDForgeflow** [comment]
@AaronHForgeFlow it's rebased now

**Pull request merged**
