### PR TITLE
Replaces #114 - Squashed commit of the following:

### LINKED ISSUE #118: Operating unit on account journals
Why is the operating unit on account journal visible only on bank and cash journals?

https://github.com/OCA/operating-unit/blob/cbcc0a597c507efe3e94322d9f3016334770a3d7/account_operating_unit/views/account_journal_view.xml#L10-L13

Would there be any drawbacks to show it on all journals?

### PR DESCRIPTION
**Pull request by richard-willdooit**
commit 42ebcc6efc35989249a3403c59f15201bde8a856
Author: Richard deMeester <richard@willowit.com.au>
Date:   Fri Jul 27 10:39:07 2018 +1000

    Remove erroneous extra currency code.

commit 921aa2c9bf87ff920bfa3debfd1b3ef534d059a5
Author: Michael Aldrin Villamar <michael.villamar@cloudemployee.co.uk>
Date:   Thu Jul 26 16:04:32 2018 +0800

    [FIX][account_payment] Fix in the internal transfers amount currency; [FIX] Allow selecting OU on all account journals

commit b6ce928dbcdd9dd706dcd86bb78babe7aeb70f88
Merge: e071cb4 b9c083c
Author: Michael Aldrin Villamar <michael.villamar@cloudemployee.co.uk>
Date:   Thu Jul 26 15:25:55 2018 +0800

    Merge branch '11.0-willdoo_account_operating_unit_module_upgrade' of github.com:WilldooIT/operating-unit into 11.0-willdoo_account_operating_unit_module_upgrade

commit b9c083ce807f0e687f40afa32dd1064a8ee9e2ab
Author: Michael Aldrin Villamar <michael.villamar@cloudemployee.co.uk>
Date:   Tue Jul 17 12:55:42 2018 +0200

    [MIG]account_operating_unit to v11

commit fd0433ec2a5eea9ac37902e53c0d37a7ccaf0862
Author: Isabel Esparza <isabel.esparza@jarsa.com.mx>
Date:   Tue Apr 10 12:20:52 2018 -0500

    [FIX][account_payment]Fix in the internal transfers amount currency

commit aa18228b9c6e7c7c329ff6d951bb08f784129bfd
Author: aaron <ahenriquez@eficent.com>
Date:   Mon Jun 11 12:02:48 2018 +0200

    [FIX]PYLINT mainly

commit cb65d729ec6c7736d1f14255b1185fc432f91a27
Author: Stéphane Bidoul (ACSONE) <stephane.bidoul@acsone.eu>
Date:   Wed May 16 14:15:40 2018 +0200

    Allow selecting OU on all account journals

    Closes #118

commit 368b1fb5ea18bf5a42ea9a5b0b245fd9df55a2ba
Author: Darshan Patel <darshan.patel.serpentcs@gmail.com>
Date:   Tue Jul 4 14:48:56 2017 +0530

    [FIX] readonly on OU

commit f5cd92b6bb707420573770ee24d749129d62ab85
Author: aheficent <ahenriquez@eficent.com>
Date:   Wed May 24 15:46:05 2017 +0200

    [FIX]When paying, the OU of the invoice should be considered only when a single invoice is being paid

commit c87013467da522364931f1abddb7d99c4bbe61c7
Author: lreficent <lois.rilo@eficent.com>
Date:   Fri Feb 10 13:25:15 2017 +0100

    [FIX] fix wrong iteration.

commit d1d0501bcb4ec327209df12131e1305410234f26
Author: Jordi Ballester Alomar <jordi.ballester@eficent.com>
Date:   Fri Feb 10 11:07:45 2017 +0100

    Add dependency on analytic_operating_unit. (#62)

    The analytic account to be selected in customer
    or supplier invoices must have the operating unit
    of the invoice as an allowed operating unit.

commit 196234c05eeced79b9cc2096dff6651b1ab6d645
Author: Jordi Ballester Alomar <jordi.ballester@eficent.com>
Date:   Mon Jan 30 11:44:07 2017 +0100

    [10.0][account_operating_unit]Add support for cash basis. Migrate to v10 nomenclature (#55)

    * Add support for cash basis. Migrate to v10 nomenclature

    * Remove apply_taxes from the create method, as in v10 this parameter is not accepted in the created method

commit 795cf8e8eb9949e922fa4e58103faa07fb3b16e5
Author: ahenriquez <ahenriquez@eficent.com>
Date:   Fri Jan 27 10:25:21 2017 +0100

    [FIX] Test remove workflow

commit 196be50ffe78a4789ace7ef3b27f980430045b27
Author: ahenriquez <ahenriquez@eficent.com>
Date:   Thu Jan 26 18:22:22 2017 +0100

    [FIX] Company view

commit aad8eb6b6bb52fec67f17f1c6fc5822f31fae4cf
Author: lreficent <lois.rilo@eficent.com>
Date:   Thu Jan 26 14:35:12 2017 +0100

    [MIG] account_operating_unit to v10.0

commit a673db6597eb406728a6949bcc1af8d6b1f9263e
Author: Pedro M. Baeza <pedro.baeza@gmail.com>
Date:   Thu Oct 6 16:04:31 2016 +0200

    [MIG] Rename manifest files

commit 7bce6b0398c68ef695b1cd90d10d4df5a0dbf3a8
Author: Pedro M. Baeza <pedro.baeza@gmail.com>
Date:   Thu Oct 6 16:04:30 2016 +0200

    [MIG] Make modules uninstallable

commit 785f7958a1f32d4047256ddaf8b605ef13ebac57
Author: jbeficent <jordi.ballester@eficent.com>
Date:   Wed Sep 28 12:10:18 2016 +0200

    [FIX] flake8

commit 11f8f661266046a54d6dcb1290ae17f3684ce08c
Author: jbeficent <jordi.ballester@eficent.com>
Date:   Fri Sep 16 16:31:48 2016 +0200

    [IMP] add security by OU on the account invoice report

commit 49f900c325d109d09cae1d688cc0f5cf8841febf
Author: jbeficent <jordi.ballester@eficent.com>
Date:   Fri Sep 16 15:54:28 2016 +0200

    [IMP] add security for account journals

commit 090e7f53d9b117a9b2cf80fcf9b218b3c8870ba9
Author: jbeficent <jordi.ballester@eficent.com>
Date:   Wed Sep 14 18:26:30 2016 +0200

    [FIX] PEP8 issues

commit ca2d3d5caac3ebc1954f5cc84a1088a3920d9c05
Author: jbeficent <jordi.ballester@eficent.com>
Date:   Wed Sep 14 17:56:27 2016 +0200

    [IMP] update readme

commit c52c8bcaf6d2f5cf6094970744f8775a730cf285
Author: jbeficent <jordi.ballester@eficent.com>
Date:   Wed Sep 14 17:54:22 2016 +0200

    [IMP] simplify headers

commit a79467274f367d594c35577f1adbf8bf7e0b2cd8
Author: jbeficent <jordi.ballester@eficent.com>
Date:   Wed Sep 14 17:41:20 2016 +0200

    [IMP] various additions, including:
    * Add management of payments using operating units
    * Trial Balance by operating units
    * Improve tests

commit d14730c9847932d60322b2edf7ee8d7f4c75abcf
Author: ahenriquez <ahenriquez@eficent.com>
Date:   Mon Sep 12 17:13:41 2016 +0200

    [FIX] travis issues

commit d8ee7d782709ca77632476ced012b01a047386bf
Author: jbeficent <jordi.ballester@eficent.com>
Date:   Fri Sep 9 19:00:34 2016 +0200

    [IMP] Add the operating units in the financial reports qweb

commit 107751adb3f45f60ddf24790873e7f38169fda33
Author: jbeficent <jordi.ballester@eficent.com>
Date:   Fri Sep 9 17:08:36 2016 +0200

    [FIX] improve README. Inter OU clearing is a balance sheet account

commit f702bb39482d31ae3bdf3dab46e7402afb39380b
Author: aheficent <ahenriquez@eficent.com>
Date:   Mon Sep 5 10:25:21 2016 +0200

    [UPT] suggested type for inter OU account

commit 9a0f0a29726f052bd32ff1a2589097523f4eb288
Author: aheficent <ahenriquez@eficent.com>
Date:   Fri Aug 26 14:54:59 2016 +0200

    [UPT] By default the OU is not self balanced because the constraint of setting an inter-OU accounts triggers  from other modules when creating companies

commit 5d98f2bfb9b0073f64bdf8a67b4db0df601b5d59
Author: aheficent <ahenriquez@eficent.com>
Date:   Thu Aug 18 18:09:24 2016 +0200

    [FIX] travis issues

commit 2d100a6d4bbec84079062b958e1781048a847964
Author: aheficent <ahenriquez@eficent.com>
Date:   Thu Aug 18 11:04:40 2016 +0200

    [FIX] travis issues

commit 50c9ade0af6a7bdc95afb4f1e3f14a012914b751
Author: aheficent <ahenriquez@eficent.com>
Date:   Thu Aug 18 10:00:01 2016 +0200

    [FIX] Style fixes suggested by @elicoidal

commit c2417e6906ea35fea28d8ec50615013f5eb53c9c
Author: aheficent <ahenriquez@eficent.com>
Date:   Wed Aug 17 18:10:07 2016 +0200

    [FIX] Do not assert_balance until all journal items exist. Fix search view in report. Other minor fixes.

commit 78984358e101220c249faefcd804bf8fc8e4169f
Author: jbeficent <jordi.ballester@eficent.com>
Date:   Thu Feb 4 19:23:47 2016 +0100

    [IMP] add invoice analysis by operating unit

commit 974313d548cd197d4f0db79fd39ea90aad384974
Author: jbeficent <jordi.ballester@eficent.com>
Date:   Mon Jan 25 11:50:45 2016 +0100

    [FIX] travis

commit cc70ba9053f6b11254229548975a8963a7558553
Author: jbeficent <jordi.ballester@eficent.com>
Date:   Mon Jan 25 11:06:47 2016 +0100

    [FIX] travis errors

commit 75c6874b5516726767d5786ea82de80bc58efa95
Author: jbeficent <jordi.ballester@eficent.com>
Date:   Mon Jan 25 10:54:45 2016 +0100

    [FIX] README.RST style

commit 0c122cfe4c967422f0724abd4807af1833b63ee3
Author: jbeficent <jordi.ballester@eficent.com>
Date:   Mon Jan 25 10:38:22 2016 +0100

    [FIX] errors in creation of account move

commit 51663f336692e4954aa81ee6d00009a3369a4b71
Author: jbeficent <jordi.ballester@eficent.com>
Date:   Mon Jan 25 09:42:27 2016 +0100

    [FIX] Applied review comments by @elicoidal

commit 79f656deee173d57c136737b420e33e5260a20d6
Author: jbeficent <jordi.ballester@eficent.com>
Date:   Fri Jan 22 18:01:36 2016 +0100

    [FIX] remove period_id

commit 25f4aa75a02505f177b49dbc3ebe6d963ae8d27b
Author: jbeficent <jordi.ballester@eficent.com>
Date:   Fri Jan 22 16:53:03 2016 +0100

    [FIX] travis errors

commit 03e7f7e4bdda2b91d0bb1f6f59248e9e0280267d
Author: Darshan Patel <darshan.patel.serpentcs@gmail.com>
Date:   Wed Jan 13 18:31:49 2016 +0530

    [IMP] Migrated and tested account_ou module to v9.

commit 573f8a60faca054a0063235b794ddc3fdbe5c8fe
Author: Darshan Patel <darshan.patel.serpentcs@gmail.com>
Date:   Tue Jan 12 19:25:47 2016 +0530

    [IMP] : Migrated the code to version 9

commit 97a0e068d27e652bf9e3ae9e3629cc5654c941ba
Author: jbeficent <jordi.ballester@eficent.com>
Date:   Wed Dec 30 12:48:37 2015 +0100

    [IMP] changed Eficent copyright

commit 1e41bcf8ba5b95bcf7fb9d70c454a67917de47b6
Author: jbeficent <jordi.ballester@eficent.com>
Date:   Wed Dec 30 12:43:29 2015 +0100

    [FIX] various fixes to ensure that unit tests pass

commit 3097d03fc6a5452eacefcd4a677dd50b747adc9c
Author: Sudhir Arya <sudhir.arya@serpentcs.com>
Date:   Wed Dec 23 19:24:56 2015 +0530

    [ADD] Added Account Operating Unit module for v9.

commit e071cb4a53ac6282a765ad70094ea5b70e1974bd
Merge: 39dbbaa 13ab9ae
Author: Michael Aldrin Villamar <michael.villamar@cloudemployee.co.uk>
Date:   Thu Jul 12 09:59:20 2018 +0800

    Merge branch '11.0' of github.com:OCA/operating-unit into 11.0-willdoo_account_operating_unit_module_upgrade

commit 39dbbaa03cd3c5c34a9de970909352d2806b2a9f
Author: Michael Aldrin Villamar <michael.villamar@cloudemployee.co.uk>
Date:   Thu Jul 12 09:58:55 2018 +0800

    [MIG] Remove analytic_operating_unit in migration

commit f4735623e1e253a1443ac8a60b891709085231e2
Author: Michael Aldrin Villamar <michael.villamar@cloudemployee.co.uk>
Date:   Tue Apr 17 08:42:37 2018 +0800

    [MIG] account_operating_unit: Migration to v11.0

commit 4a2a538743a800a2a16585ee71ce0a5a6cee80a8
Author: Michael Aldrin Villamar <michael.villamar@cloudemployee.co.uk>
Date:   Mon Apr 16 09:49:43 2018 +0800

    [MIG] analytic_operating_unit and account_operating_unit to v11.0

commit e7c707dc5295c2dbed1870679695b1ec549cc403
Author: Michael Aldrin Villamar <michael.villamar@cloudemployee.co.uk>
Date:   Mon Apr 16 09:12:52 2018 +0800

    [MIG] account_operating_unit: Migration to 11.0

commit 88daa7365d72e8ac9f472fd2c484b872ddfc40af
Author: Michael Aldrin Villamar <michael.villamar@cloudemployee.co.uk>
Date:   Mon Apr 16 08:16:42 2018 +0800

    Migrated analytic_operating_unit and account_operating_unit to 11.0

### CODE REVIEW

**Comment by richard-willdooit** [comment]
Sorry to do it this way - the rebase was becoming a headache....

**Comment by richard-willdooit** [comment]
@michael-villamar @jbeficent @aheficent 

#114 - I was having trouble rebasing - so have proposed this squashed commit...

**Comment by richard-willdooit** [comment]
@meigallodixital As well

**Comment by AaronHForgeFlow** [comment]
I am not sure whats the problem. Account_operating_unit is not still migrated.

**Comment by AaronHForgeFlow** [comment]
Thank you @richard-willdooit Do you mind if we continue on #140 ?

**Comment by richard-willdooit** [comment]
@aheficent Be my guest.

**Pull request closed without merging**
