### PR TITLE
[14.0][MIG] mis_builder_operating_unit

### PR DESCRIPTION
**Pull request by kittiu**
Standard migration.

### CODE REVIEW

**Comment by hitrosol** [comment]
i try this in my local, it works well. Can filter the report base on the OU. 
Not sure why it needs more test as the code is the same as previous version.

**Review by AaronHForgeFlow — APPROVED** [review]
LGTM

/ocabot migration mis_builder_operating_unit

**Review by marcelsavegnago — APPROVED** [review]
LGTM

**Pull request merged**
