### PR TITLE
[16.0][MIG] project_operating_unit: migration to 16.0

### PR DESCRIPTION
**Pull request by huguesdk**
depends on #576 (this is why tests are failing) and contains the last commit of #577.

### CODE REVIEW

**Review by victor-champonnois — APPROVED** [review]
Functionnal review OK

**Comment by victor-champonnois** [comment]
@huguesdk could you fix the tests ?

**Comment by alan196** [comment]
@huguesdk could you rebase 🙏 in order to test in runboat

**Comment by huguesdk** [comment]
@alan196 rebase done.

**Review by alan196 — APPROVED** [review]
Functional & Technical Review 👍

**Pull request merged**
