### PR TITLE
[14.0][MIG] migration of module operating_unit 

### PR DESCRIPTION
**Pull request by alan196**
### Proposed changes

I've migrated the module operating_unit and its functionalities from Odoo 13.0 to 14.0. I've checked if all unit tests are still running.

### Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Migration Update

### Checklist

- [x] I have read the CONTRIBUTING doc
- [x] I have signed the CLA
- [x] Lint and unit tests pass locally with my changes
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have updated the necessary documentation

### CODE REVIEW

**Review by rvalyi — APPROVED** [review]

**Review by jesus01x — APPROVED** [review]

**Comment by AaronHForgeFlow** [comment]
Thank you @alan196 for migrating this to 14.0 :rocket: 

I am wondering if you have looked at this: https://github.com/OCA/operating-unit/pull/312 For me it makes sense what he says. What do you think?

**Comment by alan196** [comment]
> Thank you @alan196 for migrating this to 14.0 🚀
> 
> I am wondering if you have looked at this: #312 For me it makes sense what he says. What do you think?

I like the change, do I want to merge that change? or I make a cherry-pick to get this change to V14?

**Comment by AaronHForgeFlow** [comment]
I think it is best to cherry-pick it. But please wait until commits on the other PR are squashed.

**Comment by AaronHForgeFlow** [comment]
0743b27eca63e23766b0a53b4ec36b39236fd7e2 could be cherry-picked now :)

**Review by AaronHForgeFlow — APPROVED** [review]
:+1:  Functional test good so far

**Pull request merged**
