### PR TITLE
[16.0] [MIG] stock_operating_unit

### PR DESCRIPTION
**Pull request by Borruso**
Migration stock_operating_unit from 15.0 to 16.0

--
Confermo di aver firmato il CLA https://odoo-community.org/page/cla e di aver letto le linee guida su https://odoo-community.org/page/contributing

### CODE REVIEW

**Review by alan196 — APPROVED** [review]
Functional and code review 👍

**Review by gurneyalex — APPROVED** [review]

**Comment by alan196** [comment]
What happened with the merge of this PR?? It fails for codecov??

**Pull request merged**
