### PR TITLE
[MIG] analytic_operating_unit: Migration to 17.0

### PR DESCRIPTION
**Pull request by ghost**
Depends on:

- [x] https://github.com/OCA/operating-unit/pull/667

### CODE REVIEW

**Comment by traitrantrobz** [comment]
I have looked it over, and it seems good to me 👍

**Review by yankinmax — APPROVED** [review]

**Review by AaronHForgeFlow — COMMENTED** [review]
Functional test LG! Thanks for the AnalyticDistribution inheritance.

Can you please remove the test-requirements.txt commit and rebase?

**Comment by yankinmax** [comment]
@jdidderen-nsi can you please remove dependency commit and rebase?
operating_unit is merged:
- [ ] https://github.com/OCA/operating-unit/pull/667

**Comment by ghost** [comment]
@yankinmax @AaronHForgeFlow And it's good to go 👍

**Review by AaronHForgeFlow — APPROVED** [review]

**Pull request merged**
