### PR TITLE
[16.0][MIG] account_operating_unit

### PR DESCRIPTION
**Pull request by hbrunn**
TODO

- [x] patch the analytic distribution widget to inject the operating unit into the analytic account domain
- [x] add tests for account.bank.statement.line

The module is already perfectly functional, but I don't consider the migration to be properly done without this

### CODE REVIEW

**Review by AaronHForgeFlow — COMMENTED** [review]
Thanks for the work @hbrunn  I think the module works ok. Only pending the 2 items you mentioned. Can you consider to incluide this? https://github.com/OCA/operating-unit/pull/658

**Review by houssine78 — APPROVED** [review]
LGTM

**Comment by AaronHForgeFlow** [comment]
To be also included: https://github.com/OCA/operating-unit/pull/685 Thanks

**Comment by hbrunn** [comment]
~~note that I won't be working on this any time soon, so whoever has a stake in this migration, please implement the missing points above and cherry pick the commits mentioned~~

**Comment by hbrunn** [comment]
@AaronHForgeFlow picked the commits you requested and added the patch for the widget

**Comment by AaronHForgeFlow** [comment]
@hbrunn  Thank you! I will do a functional review.

**Review by AaronHForgeFlow — APPROVED** [review]
Functional review, it works as expected. Thanks

**Pull request merged**
