### PR TITLE
[15.0][MIG] stock_account_operating_unit: Migration to 15.0

### PR DESCRIPTION
**Pull request by BT-apadron**

### CODE REVIEW

**Comment by BT-apadron** [comment]
This module has dependencies with **account_operating_unit** and **stock_operating_unit**. 
These ones have two Pull Request pending to approved for version 15.0: 
account_operating_unit -> https://github.com/OCA/operating-unit/pull/420 
stock_operating_unit -> https://github.com/OCA/operating-unit/pull/439

**Review by AaronHForgeFlow — APPROVED** [review]
Functional tests on runbot

**Review by JuanyDForgeflow — APPROVED** [review]

**Pull request merged**
