### PR TITLE
[17.0][MIG] hr_operating_unit: Migration to 17.0

### PR DESCRIPTION
**Pull request by traitrantrobz**
Ref: BSRD-702
Depends on:

- [x] https://github.com/OCA/operating-unit/pull/667

### CODE REVIEW

**Review by leemannd — APPROVED** [review]

**Review by ajaniszewska-dev — APPROVED** [review]

**Comment by gurneyalex** [comment]
@traitrantrobz can you clean up the merged pr now that the dependency has been released?

**Comment by traitrantrobz** [comment]
@gurneyalex Thank you for reviewed. I cleaned up the merged PR

**Pull request merged**
