### PR TITLE
[10.0] [ADD] purchase_request_qweb_operating_unit

### PR DESCRIPTION
**Pull request by nikul-serpentcs**
Purchase Request Qweb Report With Operating Unit
================================================

* This module replaces the WebKit Purchase Request report by
  a Qweb report and also adds the Operating Unit information to it.

### CODE REVIEW

**Comment by nikul-serpentcs** [comment]
@aheficent Could you please review.

**Review by AaronHForgeFlow — COMMENTED** [review]
LGTM now. Just waiting for https://github.com/OCA/operating-unit/pull/80

**Comment by LoisRForgeFlow** [comment]
Please keep commit history, see [this](https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-10.0) for more help and guidelines for migrations.

**Comment by LoisRForgeFlow** [comment]
Migration of https://github.com/OCA/operating-unit/pull/68

**Comment by AaronHForgeFlow** [comment]
Hi @nikul-serpentcs Can you split this in two different PRs? One for the generic report and one for this one. There are two other pull request waiting: #91 #92 
Thanks

**Comment by nikul-serpentcs** [comment]
`report_qweb_operating_unit` module #95 


@aheficent Could you please review.

**Comment by AaronHForgeFlow** [comment]
Superseded by #125

**Pull request closed without merging**
