### PR TITLE
[14.0][MIG] fieldservice_operating_unit

### PR DESCRIPTION
**Pull request by Vimal-OSI**

### CODE REVIEW

**Review by patrickrwilson — APPROVED** [review]
Tested, works great, LGTM

**Comment by patrickrwilson** [comment]
@smangukiya @osi-scampbell can you please help review?

**Comment by patrickrwilson** [comment]
@Vimal-OSI can you squash all the automated commits? (.pot, readme, translations)

**Review by smangukiya — APPROVED** [review]
LGTM

**Pull request merged**
