### PR TITLE
[12.0] [MIG] stock_account_operating_unit

### PR DESCRIPTION
**Pull request by bjeficent**
Migration of stock_account_operating_unit to version 12.0

### CODE REVIEW

**Review by AaronHForgeFlow — COMMENTED** [review]
Tested locally and it is working good. Will approve when green.

**Comment by nikul-serpentcs** [comment]
@bjeficent  `Mr.Travis` is :red_circle:

**Review by AaronHForgeFlow — APPROVED** [review]
:+1: LGTM

**Review by MiquelRForgeFlow — APPROVED** [review]
LGTM

**Comment by AaronHForgeFlow** [comment]
Rebasing to check CI

**Review by MiquelRForgeFlow — APPROVED** [review]
I have included https://github.com/OCA/operating-unit/pull/189.

**Review by AaronHForgeFlow — APPROVED** [review]
:+1: tested functional

**Pull request merged**
