### PR TITLE
[15.0] Migration of operating_unit

### PR DESCRIPTION
**Pull request by alan196**
### Proposed changes

Migration PR for module operating_unit.

### Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Migration Update

### Checklist

- [x] I have read the CONTRIBUTING doc
- [x] I have signed the CLA
- [x] Lint and unit tests pass locally with my changes
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have updated the necessary documentation

### CODE REVIEW

**Review by AaronHForgeFlow — APPROVED** [review]
Code review :+1:

**Review by dreispt — APPROVED** [review]

**Comment by alan196** [comment]
@dreispt Thanks for you help.

I have checked the error of the commit and is the following.

Error: reserveCache failed: Cache already exists. Scope: refs/heads/15.0-ocabot-merge-pr-418-by-dreispt-bump-nobump, Key: pre-commit-2-6e9292ce7484c9db39ab47966f1138e55cc541e71579416d61487d23def85a68-4e24adb62dbde1e332c44d9caac1332123b0c4d96b6ef06d4c2f05d92f67bb0d, Version: 28cdb9f5496f334116f23e86f0063f5d3a9348c2e22425a33171e071aadada7e

I don't know how to fix it. I run pre-commit again ant it works well... What can I do in order to complete this merge??

**Pull request merged**
