### PR TITLE
[15.0] Migration of analytic_operating_unit

### PR DESCRIPTION
**Pull request by alan196**
### Proposed changes

Migration PR for module analytic_operating_unit.

### Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Migration Update

### Checklist

- [x] I have read the CONTRIBUTING doc
- [x] I have signed the CLA
- [x] Lint and unit tests pass locally with my changes
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have updated the necessary documentation

### Comments

This module depends on https://github.com/OCA/operating-unit/pull/418

### CODE REVIEW

**Comment by alan196** [comment]
@AaronHForgeFlow could you help me to review this PR 🙏

**Review by AaronHForgeFlow — APPROVED** [review]
:+1: Functional test + code

**Review by MiquelRForgeFlow — APPROVED** [review]

**Pull request merged**
