### PR TITLE
[15.0][MIG] account_operating_unit

### PR DESCRIPTION
**Pull request by Saran440**
This pr fix bug and test script
From pr https://github.com/OCA/operating-unit/pull/420

cc: @alan196 @AaronHForgeFlow

### CODE REVIEW

**Comment by AaronHForgeFlow** [comment]
It is ok to me. @alan196 do you agree to supersede the PR here? Otherwise you can cherry-pick the last commit.

**Comment by alan196** [comment]
I'm ok with this change! No problem from my side

**Review by AaronHForgeFlow — COMMENTED** [review]
The OU are not autobalanced:
- In the company mark the checkbox OU are self-balanced
- Create an invoice for Main OU
- Create a bank journal for B2B
- Create a payment for Bank B2B
- Reconcile the invoice and the payment
- I expect here a Inter OU balance journal entry that reflects the balance that is loss in Main OU and gained in B2B

**Comment by AaronHForgeFlow** [comment]
Hi @Saran440 , 

> The OU are not autobalanced:
> 
> * In the company mark the checkbox OU are self-balanced
> * Create an invoice for Main OU
> * Create a bank journal for B2B
> * Create a payment for Bank B2B
> * Reconcile the invoice and the payment
> * I expect here a Inter OU balance journal entry that reflects the balance that is loss in Main OU and gained in B2B

This test is not entirely correct. The inter OU journal item is created only when mixing operating units in a single journal entry, not when reconciling. So please disregard this comment. Sorry for the confusion.

**Review by AaronHForgeFlow — APPROVED** [review]
LGTM! other approvals in the PR that was superseded, so I am merging soon.

**Review by alan196 — APPROVED** [review]

**Pull request merged**
