### PR TITLE
[FIX][14.0] operating unit: #503

### LINKED ISSUE #503: [14.0] operating_unit - access restrictions is not applied
## Module
operating_unit 

## Describe the bug
When you remove operating unit assigned to a product or another model from a user he still can see this record.

## To Reproduce
 - Set all operating units to a user.
 - Set 1 operating unit to a product.
 - Remove this operation unit from user.
 - Refresh page - user can see record.
 
https://recordit.co/hdnuNhKeMN

**Expected behavior**
User should not see records with operating units he has no access to.

**Additional context**
If you change any access right of a user, then access limitation will be applied. Looks like operating unit access rules is not triggered without changing groups in addition.

### PR DESCRIPTION
**Pull request by ilyasProgrammer**
fix #503

### CODE REVIEW

**Review by francesco-ooops — APPROVED** [review]
functional ok! 

@ilyasProgrammer rebase please

@AaronHForgeFlow @OCA/accounting-maintainers could you take a look?

**Review by SicurSam — APPROVED** [review]
functional ok!

**Review by AaronHForgeFlow — APPROVED** [review]

**Comment by AaronHForgeFlow** [comment]
/ocabot merge patch. Can you please check if this is needed in v15.0?

**Comment by francesco-ooops** [comment]
> /ocabot merge patch. Can you please check if this is needed in v15.0?

yes, it's needed in v15 as well, @ilyasProgrammer can you make a PR?

also @AaronHForgeFlow could you check how to fix readme.md for 14.0 as per #505 ? Thanks!

**Comment by ilyasProgrammer** [comment]
https://github.com/OCA/operating-unit/pull/514

**Comment by AaronHForgeFlow** [comment]
Thank you @ilyasProgrammer

**Pull request merged**
