### PR TITLE
14.0 mig sale stock operating unit

### PR DESCRIPTION
**Pull request by dannyadair**
This is
https://github.com/OCA/operating-unit/pull/377 (stale)
plus the fix for not being able to change warehouse
https://github.com/OCA/operating-unit/pull/377#pullrequestreview-1121699322

Depends on https://github.com/OCA/operating-unit/pull/464

### CODE REVIEW

**Comment by AaronHForgeFlow** [comment]
@dannyadair it seems there are git conflicts in the rebase, will you continue with this PR?

**Comment by dannyadair** [comment]
@AaronHForgeFlow Sorry for the delay. You should be able to merge this now.

**Comment by AaronHForgeFlow** [comment]
Thanks for the update @dannyadair  :)

Can you avoid merge commits in the branch? Perhaps you can just squash the last 3 commits in a single one.

There is an issue in the sales_team_operating_unit module that needs to be fixed in order to be able to test this correctly. I think I will do a quick fix on that one.

**Comment by AaronHForgeFlow** [comment]
I was able to work around the issue in the sales team module by deleting a reassigning the operating units to the user, then I was able to create a sales team for other operating units. The stock moves on he delivery order had as origin the correct warehouse and operating unit.

**Review by AaronHForgeFlow — COMMENTED** [review]
LGTM. Pending to fix commits only. 

@JuanyDForgeFlow can you review?

**Review by JuanyDForgeflow — APPROVED** [review]
Functional Review LGTM

**Comment by dannyadair** [comment]
> Thanks for the update @dannyadair :)
> 
> Can you avoid merge commits in the branch? Perhaps you can just squash the last 3 commits in a single one.

Thanks @AaronHForgeFlow , sorry I think this goes beyond my git fu - could you please let me know how to do it?
If I understand you right the "[FIX] Warehouse could not change" should contain all the subsequent commits as well.

I fetched the original PR #377 then pushed as my own branch by the same name.
The commits look nice and sequential in this PR but if I reset 3 commits back the squashed merge has all the changes.
https://github.com/dannyadair/operating-unit/commits/14.0-mig-sale-stock-operating-unit

I still need to get the hang of this.
Thank you for you help!

**Comment by francesco-ooops** [comment]
@AaronHForgeFlow if you could provide instructions to @dannyadair on how to fix commits, it would be great to have this module in v14!

Let us know if you need help

**Comment by AaronHForgeFlow** [comment]
Hi @dannyadair, sorry I missed your comment. I think you will have trouble to rebase your branch, because the starting commit is to far behind the HEAD branch and there is a merge commit with lots of changes. I suggest to save the code you have on a separate folder and start the migration process again. Then paste the saved code again and do a new commit.

**Comment by dannyadair** [comment]
Thanks @AaronHForgeFlow I've just changed the migration to a single commit.

**Comment by francesco-ooops** [comment]
@dannyadair unfortunately it cannot be merged in a single commit, I think you should start again by following this guide: https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-14.0#technical-method-to-migrate-a-module-from-130-to-140-branch

**Comment by dannyadair** [comment]
@francesco-ooops Thanks. I re-did all those steps in a fresh PR #584 (deleting the branch closed this one) from scratch.
I have to ask though, what's the difference? The pre-commit had nothing to do, so nothing to commit. So PR #584 is still just a single commit.

**Comment by dannyadair** [comment]
@francesco-ooops v13 PR #253 was not merged. Should I be picking up from 12?

**Comment by AaronHForgeFlow** [comment]
Hi @dannyadair, I think https://github.com/OCA/operating-unit/pull/584 has the same issue. All commit history from the beginning have to be present.  #253 commits have to be present only if you used them to migrate originally. If not then it is ok to migrate directly from 12.0.

I can fix https://github.com/OCA/operating-unit/pull/584 if you allowed administrators to push to your branch. If not, I can create a new PR instead. Just let me know.

**Comment by dannyadair** [comment]
Thanks @AaronHForgeFlow I had "Allow edits and access to secrets by maintainers" checked if that's what you mean.

I never migrated this, just added two lines to the stale #377 so I can't really say what they used/copied/created

**Comment by AaronHForgeFlow** [comment]
> Thanks @AaronHForgeFlow I had "Allow edits and access to secrets by maintainers" checked if that's what you mean.

Thanks, yes I meant that. I will fix commit history in the same PR then.
> I never migrated this, just added two lines to the stale #377 so I can't really say what they used/copied/created

Ok, I will not include that migration commit in the history then.

**Comment by dannyadair** [comment]
Thanks!

**Pull request closed without merging**
