### PR TITLE
[9.0][purchase_requisition_operating_unit]

### PR DESCRIPTION
**Pull request by JordiBForgeFlow**

### CODE REVIEW

**Review by AaronHForgeFlow — APPROVED** [review]
It works as expected :+1:

**Comment by AaronHForgeFlow** [comment]
ping @eficent

**Review by LoisRForgeFlow — APPROVED** [review]
Functional test :+1:

**Review by serpentcs-dev1 — APPROVED** [review]
Functional and Code Review LGTM :+1:

**Review by MiquelRForgeFlow — APPROVED** [review]
LGTM :+1:

**Comment by AaronHForgeFlow** [comment]
Can't wait to get this merged :star:

**Comment by AaronHForgeFlow** [comment]
@jbeficent I think this can be merged...

**Comment by AaronHForgeFlow** [comment]
Can anybody please merge this? :innocent:

**Comment by LoisRForgeFlow** [comment]
@jbeficent Please stop the deep suffering @aheficent is in... merge this please!  :pray:

**Comment by MiquelRForgeFlow** [comment]
@aheficent 😂
Suffering oblivion from your boss will make you stronger 💪

**Comment by AaronHForgeFlow** [comment]
I won't start to rob banks like someone's employee, but It would be nice to merge this taking advantage of this code sprint :smile:

**Comment by JordiBForgeFlow** [comment]
@aheficent @mreficent Ok. I can see that you are now stronger!!

**Pull request merged**
