### PR TITLE
[9.0][sale_crm_operating_unit]

### PR DESCRIPTION
**Pull request by JordiBForgeFlow**

### CODE REVIEW

**Comment by AaronHForgeFlow** [comment]
cc @eficent

**Comment by LoisRForgeFlow** [comment]
There are some changes in `account_operating_unit` in this PR, is this on purpose to fix travis or similar? or has it been a mistake?

**Comment by AaronHForgeFlow** [comment]
@lreficent The purpose wa to fix travis. The question is, why it did not fail in the PR for the account_operating_unit? :confused:

**Review by LoisRForgeFlow — APPROVED** [review]
Functional test :+1:

**Review by AaronHForgeFlow — APPROVED** [review]
Seal of approved :1st_place_medal:

**Comment by pedrobaeza** [comment]
Please squash commits before merging

**Review by MiquelRForgeFlow — APPROVED** [review]
just squash and merge already :+1:

**Pull request closed without merging**
