### PR TITLE
[15.0][FIX]-account_operating_unit: fix the error 'You are trying to …

### PR DESCRIPTION
**Pull request by hieulucky111**
[FIX] account_operating_unit: fix the error 'You are trying to reconcile some entries that are already reconciled'

"You are trying to reconcile some entries that are already reconciled"
How to reproduce the issue:

    1. Use Payment Term on Invoice, so Payable / Receivable Journal Item Line will be split to 2 lines.
    2. Register Payment to pay the first Payable / Receivable Journal Item Line.
    3. Second Register Payment will face the error above.

image

### CODE REVIEW

**Review by AaronHForgeFlow — APPROVED** [review]
Code review. LGTM

**Review by ps-tubtim — APPROVED** [review]
LGTM

**Review by jcdrubay — APPROVED** [review]
Code review: LGTM

**Pull request merged**
