### PR TITLE
[14.0][MIG] migration of module account_operating_unit

### PR DESCRIPTION
**Pull request by alan196**
### Proposed changes

I've migrated the module account_operating_unit and its functionalities from Odoo 13.0 to 14.0. I've checked if all unit tests are still running.

### Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Migration Update

### Checklist

- [x] I have read the CONTRIBUTING doc
- [x] I have signed the CLA
- [x] Lint and unit tests pass locally with my changes
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have updated the necessary documentation

### Further comments

This module depends on the operating_unit and analytic_operating_unit. That means that there should be a migration of it to 14.0. Because there is already a PR for migration I've added the changes of the PR to my local environment to test my migration.

This PR depends on the following migration PR:

https://github.com/OCA/operating-unit/pull/328
https://github.com/OCA/operating-unit/pull/331

### CODE REVIEW

**Comment by kittiu** [comment]
@alan196 can you rebase please. your `operating_unit` is now available :)

**Comment by kittiu** [comment]
@alan196 You may have noticed, this need https://github.com/OCA/operating-unit/tree/13.0/analytic_operating_unit also. And this make red travis.

Note: I am wondering, since previous version, why account_operating_unit not depends on analytic_operating_unit.

**Comment by Saran440** [comment]
Functional Test Error

Step to error
1. Create new data with demo data
2. install module account_operating_unit
Selection_001



It can fixed by install module analytic_operating_unit first.
May be sequence file is wrong, please you check?

**Comment by alan196** [comment]
@kittiu @Saran440 

I rebased the PR and add analytic_operating_unit as a dependency

**Review by kittiu — APPROVED** [review]

**Review by Saran440 — APPROVED** [review]
Functional Test :+1:

**Pull request merged**
