### PR TITLE
[12.0][FIX] res_partner_operating_unit: Fixed an issue of getting trace-back when logged In user going to change the Default Operating Unit.

### PR DESCRIPTION
**Pull request by Dangar-Serpentcs**
Fixed issue: https://github.com/OCA/operating-unit/issues/335

### CODE REVIEW

**Comment by Swapnesh-SerpentCS** [comment]
Commit message Guideline? :thinking:

**Comment by AaronHForgeFlow** [comment]
Sorry. I hit the wrong PR here. I aborted the merge.

**Comment by Dangar-Serpentcs** [comment]
> Commit message Guideline?

I just put issue number on this #PR description instead of commit message.

Now can you please review the code?

**Comment by Dangar-Serpentcs** [comment]
Hello, @Swapnesh-SerpentCS , @AaronHForgeFlow Can you please review the changes?

**Review by luc-demeyer — APPROVED** [review]

**Comment by Dangar-Serpentcs** [comment]
Thank you @luc-demeyer for approval.

**Comment by luc-demeyer** [comment]
@HirenDangar 
No problem. It's better to have this module without than with stack trace.
But imho the real solution for this module is a refactoring + renaming or removal (as documented in https://github.com/OCA/operating-unit/pull/308).

**Review by alessandrocamilli — APPROVED** [review]

**Comment by matteoopenf** [comment]
@luc-demeyer  merge?

**Review by suassa — APPROVED** [review]

**Comment by matteoopenf** [comment]
> @luc-demeyer merge?

@luc-demeyer  is it possible merge?
Thanks

**Comment by matteoopenf** [comment]
@Dangar-Serpentcs can you fix the message of the commit?

**Comment by matteoopenf** [comment]
@AaronHForgeFlow  the only problem is the message of the commit?

**Comment by AaronHForgeFlow** [comment]
/ocabot merge patch

@matteoopenf It is not the best message but I've seen others worse :) better to fix the traceback

**Comment by matteoopenf** [comment]
> /ocabot merge patch
> 
> @matteoopenf It is not the best message but I've seen others worse :) better to fix the traceback

Many thanks

**Pull request merged**
