### PR TITLE
[14.0][IMP] sale_operating_unit: allowed to hide operating_unit_id in list views

### PR DESCRIPTION
**Pull request by alexeirivera87**
added optional="hide"

### CODE REVIEW

**Comment by alexeirivera87** [comment]
Hello @AaronHForgeFlow 

Could you please check this small adjustment?

regards

**Comment by AaronHForgeFlow** [comment]
put optional="show" instead

That way there is no changes for current users.

**Comment by alexeirivera87** [comment]
@AaronHForgeFlow 

It's done.

regards

**Comment by AaronHForgeFlow** [comment]
@alexeirivera87 Thanks. You can add yourself in the the contributors.rst file but please do not change Readme.rst file. The oca bot will do that.

**Review by robyf70 — COMMENTED** [review]
LGTM

**Comment by alexeirivera87** [comment]
> @alexeirivera87 Thanks. You can add yourself in the the contributors.rst file but please do not change Readme.rst file. The oca bot will do that.

@AaronHForgeFlow 
Ah, copied. I did not know that. Should I revert the change in the readme file? In order to get this PR approved/merged?

**Comment by AaronHForgeFlow** [comment]
@alexeirivera87 no, it is not that important

**Comment by AaronHForgeFlow** [comment]
I don't mind to merge it just waiting for some other users to approve

**Comment by alexeirivera87** [comment]
Hello @MiquelRForgeFlow 

I saw you approved other PR in this repository. Could you please check this one? Thanks in advance.

**Comment by alexeirivera87** [comment]
Hello @AaronHForgeFlow 

Can this PR be merged?

regards

**Review by AaronHForgeFlow — APPROVED** [review]

**Comment by AaronHForgeFlow** [comment]
ok, let's do it, it is a minor change. The other needed approval is implicit in the other comment.

/ocabot merge minor

**Pull request merged**
