### PR TITLE
[15.0][IMP]mis_builder_operating_unit Filter account entries not having operating unit

### PR DESCRIPTION
**Pull request by AaronHForgeFlow**
FW #651

### CODE REVIEW

**Review by robyf70 — APPROVED** [review]
LGTM

**Comment by AaronHForgeFlow** [comment]
There is some issue in the account_operating_unit module, tests are failing

**Comment by robyf70** [comment]
> There is some issue in the account_operating_unit module, tests are failing

The issue is raised as

**raise ValidationError(_("The selected payment method is not available for this payment, please select the payment method again."))**

see here https://github.com/OCA/operating-unit/actions/runs/8170230486/job/22335955970?pr=653#step:8:733

**Comment by AaronHForgeFlow** [comment]
I will check when having some time.

**Comment by robyf70** [comment]
> I will check when having some time.

I've committed the fix see #654

**Comment by AaronHForgeFlow** [comment]
Thank you @robyf70  this is green now :)

**Comment by robyf70** [comment]
> Thank you @robyf70 this is green now :)

Any chance to get it merged?

**Comment by robyf70** [comment]
@AaronHForgeFlow Can apply the changes as per #651 so we have all uniform?

**Comment by AaronHForgeFlow** [comment]
@robyf70 sure! in any case this should not me merged until the other is merged

**Review by MiquelRForgeFlow — APPROVED** [review]

**Comment by AaronHForgeFlow** [comment]
keeping branches even
/ocabot merge minor

**Pull request merged**
