### PR TITLE
[MIG] mis_builder_operating_unit: Migration to 13.0

### PR DESCRIPTION
**Pull request by hbrunn**

### CODE REVIEW

**Comment by AaronHForgeFlow** [comment]
It seems we have to add the operating unit to the mis_builder_item model? I am getting this on runbot (running demo expenses mis report):

```
  File "/home/odoo/dependencies/mis-builder/mis_builder/models/mis_report_instance.py", line 806, in compute
    kpi_matrix = self._compute_matrix()
  File "/home/odoo/dependencies/mis-builder/mis_builder/models/mis_report_instance.py", line 799, in _compute_matrix
    self._add_column(aep, kpi_matrix, period, period.name, description)
  File "/home/odoo/dependencies/mis-builder/mis_builder_budget/models/mis_report_instance.py", line 77, in _add_column
    aep, kpi_matrix, period, label, description
  File "/home/odoo/dependencies/mis-builder/mis_builder_budget/models/mis_report_instance.py", line 54, in _add_column_mis_budget
    period.date_from, period.date_to, base_domain
  File "/home/odoo/dependencies/mis-builder/mis_builder/models/mis_kpi_data.py", line 89, in _query_kpi_data
    for item in self.search(domain):
  File "/.repo_requirements/odoo/odoo/models.py", line 1618, in search
    res = self._search(args, offset=offset, limit=limit, order=order, count=count)
  File "/.repo_requirements/odoo/odoo/models.py", line 4406, in _search
    query = self._where_calc(args)
  File "/.repo_requirements/odoo/odoo/models.py", line 4135, in _where_calc
    e = expression.expression(domain, self)
  File "/.repo_requirements/odoo/odoo/osv/expression.py", line 677, in __init__
    self.parse()
  File "/.repo_requirements/odoo/odoo/osv/expression.py", line 858, in parse
    raise ValueError("Invalid field %r in leaf %r" % (left, str(leaf)))
ValueError: Invalid field 'operating_unit_id' in leaf "<osv.ExtendedLeaf: ('operating_unit_id', 'in', [1]) on mis_budget_item (ctx: )>"
```

**Comment by kittiu** [comment]
@hbrunn what is the status of this PR? Do you plan to continue?

**Comment by hbrunn** [comment]
I've missed @AaronHForgeFlow's comment, budget items indeed don't work, but that's out of the scope of the migration. This will need a rebase indeed to fix the conflict

**Comment by kittiu** [comment]
> I've missed @AaronHForgeFlow's comment, budget items indeed don't work, but that's out of the scope of the migration. This will need a rebase indeed to fix the conflict

Will you? :)

I create this PR to attend @AaronHForgeFlow comment - https://github.com/OCA/operating-unit/pull/375

**Comment by hbrunn** [comment]
@kittiu done

**Review by AaronHForgeFlow — APPROVED** [review]
works well when budgets are not involved :+1:

**Comment by AaronHForgeFlow** [comment]
@kittiu do you agree with this?

**Comment by kittiu** [comment]
Sure!

**Review by MiquelRForgeFlow — APPROVED** [review]
LGTM

**Pull request merged**
