### PR TITLE
[12.0] [MIG] mrp_operating_unit

### PR DESCRIPTION
**Pull request by bjeficent**
Migration of module mrp_operating_unit to v12

### CODE REVIEW

**Comment by AaronHForgeFlow** [comment]
Added admin user to MianOU and b2b
In Inventory > Configuration activate routes and locations
I can see the stock_rules of other operating units:
image

**Comment by bjeficent** [comment]
> Added admin user to MianOU and b2b
> In Inventory > Configuration activate routes and locations
> I can see the stock_rules of other operating units:
> image

The Manager can see the Stock Rules of other Operating Units but he can't edit them. If you try to click on one of them you will receive a configuration error. I don't think this is an important issue, cause only the Manager could see the stock rules. Anyways, I have updated the roadmap of the stock_operating_unit.
Thanks for the review :smile:

**Review by AaronHForgeFlow — CHANGES_REQUESTED** [review]
Assign admin to OU B2b
Tried to create Manufacturing order for b2b (did not change source or destination locations)
:boom: :boom: :boom: :boom: :boom: :boom: :boom: :boom: :boom: :boom: :boom: :boom: :boom: :boom: :boom: :boom: 
image

**Review by AaronHForgeFlow — APPROVED** [review]
Functional review LGTM :+1:

**Review by MiquelRForgeFlow — APPROVED** [review]
LGTM

**Pull request merged**
