### PR TITLE
[15.0][ADD] purchase_stock_operating_unit

### PR DESCRIPTION
**Pull request by Saran440**
This module is used to integrated between Purchase and Stock to send
Operating Unit in the warehouse that has been selected from Deliver To to Stock Picking.

- When confirm order in purchase, picking will have operating unit from warehouse of picking type
Selection_034

- Check constraint that operating unit on purchase and operating unit on warehouse of picking type is not equal. it will error
Selection_035

Depend on:
- [x] purchase_operating_unit
- [x] stock_operating_unit

### CODE REVIEW

**Comment by AaronHForgeFlow** [comment]
LG! can you just avoid merge commits in the history?
This will probably be needed in v13.0 and 14.0

**Comment by Saran440** [comment]
@AaronHForgeFlow Fixed. Thank you for help :) and I can backport to v14 if someone need.

**Review by JuanyDForgeflow — APPROVED** [review]
Code + Functional LGTM

**Comment by AaronHForgeFlow** [comment]
> @AaronHForgeFlow Fixed. Thank you for help :) and I can backport to v14 if someone need.

Thank you. I just checked and I think it is not needed in v14.0

**Review by AaronHForgeFlow — APPROVED** [review]
Code review

**Pull request merged**
