### PR TITLE
[16.0] Migration of sales_team_operating unit

### PR DESCRIPTION
**Pull request by alan196**
This PR supersedes https://github.com/OCA/operating-unit/pull/592

I have removed the domain of company_id in operating unit, this is defined by the ir.rule of module operating_unit, so it's not needed.

This raises errors as in V16 the field company_id belongs to a group, and give error on installation.

### CODE REVIEW

**Review by AaronHForgeFlow — APPROVED** [review]
Functional LG!

**Comment by alan196** [comment]
@EduardoJarsa @YahairaCVJarsa could you help me to review this PR 🙏

**Review by EduardoJarsa — COMMENTED** [review]
Functional review, everything looks working

**Review by EduardoJarsa — APPROVED** [review]
Functional review, everything looks working

**Review by EduardoJarsa — CHANGES_REQUESTED** [review]
Functional review, everything looks working

**Review by EduardoJarsa — APPROVED** [review]
Functional review, everything looks working

**Review by YahairaCVJarsa — APPROVED** [review]

**Review by YahairaCVJarsa — APPROVED** [review]

**Pull request merged**
