### PR TITLE
[15.0][FIX] account_operating_unit: re reconcile payment for case self balance only

### PR DESCRIPTION
**Pull request by Saran440**
Reference : https://github.com/OCA/operating-unit/pull/423/files

This pr is fixed for not re reconcile if payment is not self balance
because may be other module will have a issue if payment is set to draft

### CODE REVIEW

**Review by AaronHForgeFlow — APPROVED** [review]
Code review LG!

**Review by ps-tubtim — APPROVED** [review]
LGTM.

**Comment by AaronHForgeFlow** [comment]
Can you include the module name in the commit message? sorry for the nitpicking

**Comment by Saran440** [comment]
@AaronHForgeFlow Fixed :)

**Pull request merged**
