### PR TITLE
[14.0][FIX] purchase_operating_unit, wrong context

### PR DESCRIPTION
**Pull request by kittiu**
The wrong context ignore {'default_state': 'draft}, which make `product_id` readonly on confirmed PO.

After this fix, now, it is possible to select product once again.

image

### CODE REVIEW

**Comment by kittiu** [comment]
@AaronHForgeFlow @ps-tubtim 
this can be FFW.

**Review by newtratip — APPROVED** [review]
Ok for me

**Review by AaronHForgeFlow — APPROVED** [review]
:+1:

**Comment by kittiu** [comment]
This is the quickest approved PR ever. Thanks guys :kiss:

**Pull request merged**
