### PR TITLE
[17.0][MIG] operating_unit_access_all: Migration to 17.0

### PR DESCRIPTION
**Pull request by traitrantrobz**
Ref: BSRD-702
Depends on:

- [x] https://github.com/OCA/operating-unit/pull/667

### CODE REVIEW

**Review by leemannd — APPROVED** [review]

**Comment by yankinmax** [comment]
@jdidderen-nsi can you please remove dependency commit and rebase?
operating_unit is merged:
- [ ] https://github.com/OCA/operating-unit/pull/667

**Comment by nguyenminhchien** [comment]
> @jdidderen-nsi can you please remove dependency commit and rebase? operating_unit is merged:
> 
>     * [ ]  [[MIG] operating_unit: Migration to 17.0 #667](https://github.com/OCA/operating-unit/pull/667)

@traitrantrobz please rebase this PR. Thanks.

**Review by yankinmax — APPROVED** [review]

**Comment by yankinmax** [comment]
@AaronHForgeFlow can you pls trigger a merge here, PR seems to be finished and approved.

**Pull request merged**
