### PR TITLE
[14.0][MIG] agreement_operating_unit

### PR DESCRIPTION
**Pull request by Vimal-OSI**

### CODE REVIEW

**Comment by patrickrwilson** [comment]
@Vimal-OSI can you squash the few bot commits?

**Comment by Vimal-OSI** [comment]
> @Vimal-OSI can you squash the few bot commits?

Suggested changes are done

**Review by patrickrwilson — APPROVED** [review]
Tested and works. Code looks good. LGTM

**Comment by patrickrwilson** [comment]
@osi-scampbell @smangukiya can you please review?

**Comment by newtratip** [comment]
Hello @Vimal-OSI,

If possible, Could you split this to 2 modules ? `agreement_operating_unit` and `agreement_serviceprofile_operating_unit`

For my project, I install agreement module (agreement_legal is extention module) but not installed agreement_serviceprofile module.

And I need to OU for the agreement (not include serviceprofile)

WDYT ?

**Comment by patrickrwilson** [comment]
Hi @newtratip it's probably best to migrate as it is now since this is how it was used in previous version and migrations typically don't include feature changes. But once it's migrated, then it can be split into two separate modules. That way the change is properly tracked and not part of a migration.

**Comment by smangukiya** [comment]
@newtratip thanks for your input on this we should definitely split this module accordingly, but as @patrickrwilson has said we should do that after this migration work done. For more cleaner approach.
Thanks

**Review by smangukiya — APPROVED** [review]

**Comment by newtratip** [comment]
okay @smangukiya @patrickrwilson

**Review by newtratip — APPROVED** [review]
LGTM :+1:

**Pull request merged**
