### PR TITLE
[IMP] account_operating_unit: Use the user OU if the journal doesn't …

### PR DESCRIPTION
**Pull request by gustavovalverde**
…have it

### CODE REVIEW

**Comment by AaronHForgeFlow** [comment]
I am not sure. If we have different bank journals for different operating units then all of them should have an operating unit assigned. Maybe it is better to add a constraint to accomplish that, but not sure also.

**Comment by gustavovalverde** [comment]
@aheficent There are 2 scenarios, both supported by this PR:
1- One journal to be used by different operating units
2- A journal per operating unit


For both use cases, the operating unit used by the payment is the one set in the journal; if the journal doesn't have it, then use the one in the user.

Without the PR, use case 1 can't be accomplished. With the PR I'm not seeing how use case 2 gets affected.

**Comment by AaronHForgeFlow** [comment]
In case 1, which operating unit pays the bill? It needs to be one only one operating unit. Even if the operating unit is fully dedicated to pay the bills of the other operating units.

**Comment by gustavovalverde** [comment]
Case 1, in a real life scenario:
#### Operating Units
- Administration
- Branch 1
- Branch 2
- Branch 3

### Journals
- Cash (no operating unit)
- Bank A (Branch 1)

All branches (OU) register their respective expenses. Financially, the cash used comes from the same source/account, so there's not need for multiple journals.

Each OU pays their bill, selecting the **Cash** journal. As the journal has no OU, the OU used on the payment is the one from the user registering the payment.

Maybe and additional validation could be that a payment from an OU, can't pay a bill from another.

**Comment by AaronHForgeFlow** [comment]
I understand that case. Perhaps you are right. Any way I think it is a good idea to have three cash journals for every OU. 

An OU can pay bills from the other, for example, administration can pay the bills of all others. Then, if OUs are self balanced an extra journal items is created to balance.

But in any case, I think this PR will not affect that use case, so I will not block this.

**Comment by gustavovalverde** [comment]
I signed the CLA, what else is needed so this PR can be merged? cc: @pedrobaeza

**Comment by blaggacao** [comment]
#193 Should solve this quite elegantly. Journals are metadata. Period.

**Comment by gustavovalverde** [comment]
ping @jbeficent @pedrobaeza

**Comment by andres-pcg** [comment]
Any update on this one? @pedrobaeza

**Comment by pedrobaeza** [comment]
I'm not involved in this repo, so you should ping another person

**Pull request closed without merging**
