### PR TITLE
[MIG] report_qweb_operating_unit: Migration to 17.0

### PR DESCRIPTION
**Pull request by ghost**
In the case of this migration, I extended the module to have the same layouts as the standard ones and almost the same capabilities as a company.

IMO a potential improvement would be to have a layout by operating unit and not just by company.

Depends on:

- [x] https://github.com/OCA/operating-unit/pull/667

### CODE REVIEW

**Comment by AaronHForgeFlow** [comment]
Thank you for the work! LG!

**Review by hbrunn — APPROVED** [review]
great initiative with the report fields on OUs, I base the v16 migration on your work.

Please cherry pick https://github.com/OCA/operating-unit/pull/699/commits/a82200d42e3e57933d8cda501737b5412036a933 for tests

**Comment by ghost** [comment]
> great initiative with the report fields on OUs, I base the v16 migration on your work.
> 
> Please cherry pick [a82200d](https://github.com/OCA/operating-unit/commit/a82200d42e3e57933d8cda501737b5412036a933) for tests

@hbrunn And it's cherry-picked. I only adapted a bit the unit test to use the Operating Unit common class.

**Review by AaronHForgeFlow — APPROVED** [review]
LGTM!

**Pull request merged**
