### PR TITLE
[14.0][FIX] purchase_operating_unit: Fix warning from an onchange function returning domain. Use domain fi…

### PR DESCRIPTION
**Pull request by Ppamungkas**
…eld instead.

### CODE REVIEW

**Comment by AaronHForgeFlow** [comment]
Can you please include the module name in the commit message? for example:

`[FIX] purchase_operating_unit: Fix warning from an onchange function returning domain. Use domain field instead.`

**Comment by Ppamungkas** [comment]
@AaronHForgeFlow sorry for the mess, I just need to get a hang on it with trial and error...

**Review by AaronHForgeFlow — APPROVED** [review]
@Ppamungkas  thanks for attend the comments. I think this is good :+1:

**Review by MiquelRForgeFlow — APPROVED** [review]

**Pull request merged**
