### PR TITLE
[15.0][mig]-report_qweb_operating_unit

### PR DESCRIPTION
**Pull request by JuanyDForgeflow**
@ForgeFlow 

Removed clean and background templates since they're not on 15.0

### CODE REVIEW

**Review by AaronHForgeFlow — APPROVED** [review]
Functional review

**Comment by Saran440** [comment]
Functional Test. I found error

Step to error
1. Install module `report_qweb_operating_unit` and `account`
2. Go to Settings > Companies > Configure Document Layout
Selection_015
3. It will error
Selection_016

**Comment by tiagor-exo** [comment]
to fix this error you need to replace all the `<t t-if="'operating_unit_id' in o.fields_get()"> `to `<t t-if="o and 'operating_unit_id' in o.fields_get()">`

**Comment by AaronHForgeFlow** [comment]
@JuanyDForgeflow , can you check?

**Comment by JuanyDForgeflow** [comment]
@tiagosrangel thanks! it works now
@AaronHForgeFlow @Saran440  please try again

**Review by Saran440 — APPROVED** [review]
LGTM :+1:

**Pull request merged**
