### PR TITLE
[17.0][FIX] res_partner_operating_unit: Fix error when create new user

### PR DESCRIPTION
**Pull request by sbiosca-s73**
When register new user, if the user not have any `default_operating_unit_id`, show this error.
image

To fix it, I add new condition for check `user_ou` has value.

### CODE REVIEW

**Comment by AaronHForgeFlow** [comment]
Thanks. Don't change the version number please, the bot will do it.

**Comment by sbiosca-s73** [comment]
@AaronHForgeFlow Done!

**Review by AaronHForgeFlow — APPROVED** [review]
LGTM

**Comment by AaronHForgeFlow** [comment]
Hi @jdidderen-nsi , you migrated the module, are you ok with the change?

**Review by gurneyalex — APPROVED** [review]

**Pull request merged**
