### PR TITLE
[14.0][FIX] sale_operating_unit: fix perfomance issues in sale order

### PR DESCRIPTION
**Pull request by alan196**
This is a forward port to this PR https://github.com/OCA/operating-unit/pull/510

### CODE REVIEW

**Comment by alan196** [comment]
@LoisRForgeFlow @moylop260 Could you help me to review this PR 🙏

**Review by AaronHForgeFlow — APPROVED** [review]
Merging to keep the branches aligned.

/ocabot merge minor

**Comment by AaronHForgeFlow** [comment]
@alan196 can you please do the same in 15.0?

**Comment by alan196** [comment]
> @alan196 can you please do the same in 15.0?

This was added in the migration PR of 15.0, it is not required

**Comment by AaronHForgeFlow** [comment]
ok! thanks for checking

**Pull request merged**
