### PR TITLE
[10.0][FIX] Account_operating_unit: Fix wrong iteration

### PR DESCRIPTION
**Pull request by LoisRForgeFlow**
Small fix.

### CODE REVIEW

**Comment by LoisRForgeFlow** [comment]
cc @darshan-serpent @aheficent

**Review by serpentcs-dev1 — APPROVED** [review]
:+1:

**Review by AaronHForgeFlow — APPROVED** [review]
:+1: Thank you @lreficent

**Review by elicoidal — APPROVED** [review]
:+1: 
BTW: please use the review function to approve PR @aheficent @darshan-serpent

**Pull request merged**
