### PR TITLE
[11.0] mig analytic operating unit

### PR DESCRIPTION
**Pull request by gdgellatly**
Depends on:

- [x] #99 operating_unit
- [x] #100 - sale_team_operating_unit

Straightforward port except I accidentally moved a field from sales_team_ou in this repo to keep the interface of analytic and sales_team the same.  Hopefully its OK as the git is painful all these little modules.

The only changes is removing encodings, bumping version, and fixing Docs typos.

### CODE REVIEW

**Comment by gdgellatly** [comment]
Review URL https://github.com/OCA/operating-unit/pull/101/files/35412115ec9f4569fa832b5ae1b400f7fa943d78..628667b02400c3f59c9a7e81b03ab13247197e87 to make easier for reviewers

**Review by AaronHForgeFlow — APPROVED** [review]
:+1: Tested on local

OBS: The commits related other PRs should me removed when it's ready to merge

**Review by simahawk — CHANGES_REQUESTED** [review]
same here, pls drop #99 commits

**Comment by simahawk** [comment]
@gdgellatly #99 got merged: you can rebase :wink:

**Comment by gdgellatly** [comment]
Sorry lost prior commits in force push - will fix it up

**Comment by gdgellatly** [comment]
@simahawk @aheficent sorry got so busy all of a sudden never got back to this.  Commit history fixed.

**Comment by meigallodixital** [comment]
What is pending for this PR to be accepted? History appears fixed.

**Comment by AaronHForgeFlow** [comment]
@meigallodixital it just need more reviewers.

@simahawk can you update your review?

**Comment by simahawk** [comment]
ops, sorry, I missed the update from @gdgellatly :sweat_smile:

**Review by simahawk — APPROVED** [review]

**Comment by simahawk** [comment]
@meigallodixital you can review as well :wink:

**Comment by meigallodixital** [comment]
@simahawk I don't feel I've the necessary experience for it :)

**Comment by simahawk** [comment]
@meigallodixital you could catch typos just to start. Or provide functional feedback (testing on runbot for instance).
In any case: the more you do it, the more you learn and get you use to it :wink:

**Comment by meigallodixital** [comment]
@simahawk We intend to use operating unit modules to simulate physical stores and do all the management in them. Shops are independent entities inside the company. They buy, sell, manage their employees and their stock themselves.

So to test and report is not going to be a problem ;) Another thing is to review and correct your code, it is another level: P.

**Comment by AaronHForgeFlow** [comment]
@meigallodixital that's fine, you can do a functional review, that's perfectly valid, your review will count.

**Comment by gdgellatly** [comment]
@meigallodixital Code review is easy, functional reviews is always what we need more of.  I much rather see review asking, why does this do this, or where is this menu, will this work with this module etc than always static code reviews.  Most of my own reviews are functional, rather than reading code.

**Comment by meigallodixital** [comment]
We still do not have 100% accounting working, but apparently nothing fails in this addon. We have tried to create analytical accounts with Operating unit, filter them, etc and it seems to work all ok. Tried with multi-company too.

Something to test to confirm?

**Comment by gdgellatly** [comment]
@meigallodixital Analytics get used everywhere so this module is a dependency for most of them.  Yeah it doesn't do much.

**Comment by meigallodixital** [comment]
The only thing we have seen (we do not know if it is a bug or feature) is that in the list view of analytical accounts there is no operating unit column. The rest of functionality seems to work perfect.

I try to do a codereview to see if I do not break anything ;)

**Review by meigallodixital — APPROVED** [review]
On OCB all appears working perfect

**Comment by pedrobaeza** [comment]
We can merge then as is and possible improvements on successive PRs

**Pull request merged**
