### PR TITLE
[MIG] 13.0 Migration of module hr_expense_operating_unit

### PR DESCRIPTION
**Pull request by alan196**
Depends on https://github.com/OCA/operating-unit/pull/229

### CODE REVIEW

**Review by lmgr0312 — APPROVED** [review]
:+1:

**Review by AaronHForgeFlow — CHANGES_REQUESTED** [review]
I think I've found a bug (probably it is also in v12). I created an expense report for "Main Operating Unit" with some expense lines for "Main Operating Unit". Then I changed the operating unit of the expense report to "B2B". However, the operating unit of the expense line remain as "Main Operating Unit". Seems incorrect.

**Comment by alan196** [comment]
@AaronHForgeFlow I fix the bug you mention. Could you help me to review again :pray:

**Review by AaronHForgeFlow — APPROVED** [review]
:+1: Functional test. Merging as soon as green Thanks

**Pull request merged**
