### PR TITLE
Reduce the width of dependency from analytic_operating_unit to operat…

### PR DESCRIPTION
**Pull request by glitchov**
Analytic has nothing to do with this module but operating_unit well.

### CODE REVIEW

**Review by luc-demeyer — APPROVED** [review]

**Review by AaronHForgeFlow — APPROVED** [review]
The account module depends on analytic module. That is why the dependency was included at first. But technically speaking it is not necessary. I guess that should be enough to remove the dependency.

**Comment by pedrobaeza** [comment]
There has been a problem with merge bot, but it's fixed now, so you can relaunch.

**Pull request merged**
